                <section id="content">
                    
                    <?php if(!Zend_Auth::getInstance()->hasIdentity()){?>
                    <div class="bannercontainer" >
                        <div class="banner" >
                            <ul>


                                <!-- THE FIRST SLIDE -->
                                <li data-transition="fade" data-slotamount="10" data-masterspeed="300" data-link="#" data-target="_blank" data-slideindex="back" >
                                    <!-- THE MAIN IMAGE IN THE SLIDE -->
                                    <img src="<?= $this->baseUrl() ?>/desktop/images/slides/sli1.jpg" alt=""/>

                                    <!-- THE CAPTIONS OF THE FIRST SLIDE -->

                                    <div class="caption randomrotate"
                                         data-x="106"
                                         data-y="90"
                                         data-speed="150"
                                         data-start="900"
                                         data-easing="easeOutExpo"  ><img src="<?= $this->baseUrl() ?>/desktop/images/slides/t-shirt1.png" alt="Image 3"/></div>

                                    <div class="caption randomrotate"
                                         data-x="390"
                                         data-y="12"
                                         data-speed="150"
                                         data-start="1800"
                                         data-easing="easeOutExpo"  ><img src="<?= $this->baseUrl() ?>/desktop/images/slides/t-shirt3.png" alt="Image 2"/></div>

                                    <div class="caption randomrotate"
                                         data-x="650"
                                         data-y="85"
                                         data-speed="150"
                                         data-start="2700"
                                         data-easing="easeOutExpo"  ><img src="<?= $this->baseUrl() ?>/desktop/images/slides/t-shirt2.png" alt="Image 1"/></div>
                                    <div class="caption randomrotate"
                                         data-x="890"
                                         data-y="130"
                                         data-speed="150"
                                         data-start="3600"
                                         data-easing="easeOutExpo"  ><img src="<?= $this->baseUrl() ?>/desktop/images/slides/t-shirt4.png" alt="Image 1"/></div>                                    
                                </li>

                                <!-- THE SECOND SLIDE -->
                                <li data-transition="fade" data-slotamount="15" data-masterspeed="300" data-delay="9400">
                                    <!-- THE MAIN IMAGE IN THE SLIDE -->
                                    <img src="<?= $this->baseUrl() ?>/desktop/images/slides/sli1.jpg" alt=""/>

                                    <div class="caption randomrotate"
                                         data-x="920"
                                         data-y="40"
                                         data-speed="150"
                                         data-start="1800"
                                         data-easing="easeOutExpo"  ><img src="<?= $this->baseUrl() ?>/desktop/images/slides/plate.png" alt="Image 6"/></div>

                                    <div class="caption randomrotate"
                                         data-x="610"
                                         data-y="40"
                                         data-speed="150"
                                         data-start="2700"
                                         data-easing="easeOutExpo"  ><img src="<?= $this->baseUrl() ?>/desktop/images/slides/cup.png" alt="Image 3"/></div>

                                    <div class="caption randomrotate"
                                         data-x="10"
                                         data-y="85"
                                         data-speed="150"
                                         data-start="900"
                                         data-easing="easeOutExpo"  ><img src="<?= $this->baseUrl() ?>/desktop/images/slides/clock.png" alt="Image 4"/></div>
                                   
                                    <div class="caption randomrotate"
                                         data-x="300"
                                         data-y="85"
                                         data-speed="150"
                                         data-start="3600"
                                         data-easing="easeOutExpo"  ><img src="<?= $this->baseUrl() ?>/desktop/images/slides/cup3.png" alt="Image 5"/></div>


                                </li>

								<!-- THE THIRD SLIDE -->
                                <li data-transition="fade" data-slotamount="15" data-masterspeed="300" data-delay="9400">
                                    <!-- THE MAIN IMAGE IN THE SLIDE -->
                                    <img src="<?= $this->baseUrl() ?>/desktop/images/slides/sli1.jpg" alt=""/>

                                    <!-- THE CAPTIONS OF THE FIRST SLIDE -->

                                    <div class="caption randomrotate"
                                         data-x="20"
                                         data-y="75"
                                         data-speed="300"
                                         data-start="1800"
                                         data-easing="easeOutExpo"  ><img src="<?= $this->baseUrl() ?>/desktop/images/slides/magnet2.png" alt="Image 6"/></div>

                                    <div class="caption randomrotate"
                                         data-x="900"
                                         data-y="89"
                                         data-speed="600"
                                         data-start="900"
                                         data-easing="easeOutExpo"  ><img src="<?= $this->baseUrl() ?>/desktop/images/slides/magnet.png" alt="Image 4"/></div>                                  
                                    <div class="caption randomrotate"
                                         data-x="600"
                                         data-y="15"
                                         data-speed="300"
                                         data-start="2700"
                                         data-easing="easeOutExpo"  ><img src="<?= $this->baseUrl() ?>/desktop/images/slides/visit-card2.png" alt="Image 5"/></div>

                                    <div class="caption randomrotate"
                                         data-x="350"
                                         data-y="10"
                                         data-speed="600"
                                         data-start="3600"
                                         data-easing="easeOutExpo"  ><img src="<?= $this->baseUrl() ?>/desktop/images/slides/visit-card1.png" alt="Image 4"/></div>                                    


                                </li>
		

                            </ul>
                            <div class="tp-bannertimer tp-bottom"></div>
                        </div>
                    </div><?php } ?>

                    <div class="content-row">
                        <div class="container">
                            <form class="search-form">
                                <div class="sixteen columns omega">
                                    
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="content-row1">
                        



                        <div class="container">
                            <div class="sixteen columns">
                                <div class="divider"></div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="container">
                           
                    <?php if(Zend_Auth::getInstance()->hasIdentity()){
                            echo $this->form;
                      }else{ 
                            echo $this->content; 
                    
                    }      ?>
                       </div></br>    
         <?php if(!Zend_Auth::getInstance()->hasIdentity()){ ?>                       
                    <div class="container">
                        <div class="sixteen columns">
                            <div class="map_row">
                                <img src="<?= $this->baseUrl() ?>/desktop/images/map.png" alt=""/>
                                <div class="inner">
                                    <h2 class="subscribe-form-title">Оставайтесь с нами</h2>

                                    <div class="notice">* Мы ценим ваше время</div>
                                </div>
                            </div>
                        </div>
                    </div>
          <?php } ?>              
                </section>

            
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery-2.0.0.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery-migrate-1.1.1.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/raphael-min.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.validationEngine.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.validationEngine-en.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.form.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.hoverdir.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.selectik.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.isotope.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/touchTouch.jquery.js"></script>
        <script src="http://twitterjs.googlecode.com/svn/trunk/src/twitter.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.carouFredSel-6.2.1.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/tabs.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/toggles.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/boxes.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/settings-panel.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.cookie.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/script.js"></script>              
                   
        <script type="text/javascript">
             CKEDITOR.replace( 'text_field' );
        </script>

 <script type="text/javascript">
$(document).ready(function(){
   //remove class
   $('#contacts').removeClass('active');
   $('#services').removeClass('active');
   $('#gallery').removeClass('active');
   $('#feedback').removeClass('active');
   //add
   $('#index').addClass('active');
});
</script>   